CREATE USER proxy_user
  IDENTIFIED BY proxy_user
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

GRANT CONNECT TO proxy_user;
GRANT RESOURCE TO proxy_user;
GRANT CREATE SESSION TO proxy_user;


ALTER USER DOME_MON01 GRANT CONNECT THROUGH proxy_user;
