--set password and tablespaces for a new user
CREATE USER DOME IDENTIFIED BY <password here>
 DEFAULT TABLESPACE SYSTEM
 TEMPORARY TABLESPACE TEMP
 PROFILE "DEFAULT";

--set quota on tablespace
ALTER USER DOME QUOTA UNLIMITED ON SYSTEM;


--basic grants and roles
GRANT CREATE JOB TO DOME;

GRANT CREATE PROCEDURE TO DOME;

GRANT CREATE SEQUENCE TO DOME;

GRANT CREATE SESSION TO DOME;

GRANT CREATE SYNONYM TO DOME;

GRANT CREATE TABLE TO DOME;

GRANT CREATE TRIGGER TO DOME;

GRANT CREATE TYPE TO DOME;

GRANT CREATE VIEW TO DOME;

GRANT SELECT ON dba_objects TO DOME;

GRANT EXECUTE ON dbms_crypto TO DOME;


GRANT "APEX_ADMINISTRATOR_READ_ROLE" TO DOME;
GRANT "CONNECT" TO DOME;
GRANT "RESOURCE" TO DOME;

